repos:
- repo: https://github.com/asottile/add-trailing-comma
  rev: v1.0.0
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.1
  hooks:
  - id: trailing-whitespace
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.7
  hooks:
  - id: flake8
